config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
  resources :rooms, except: %i[edit update destroy] do
    get 'join', on: :collection
  end

  resource :messages, only: %i[create]

  resources :users, except: %i[index, destroy]
  resource :sessions, only: %i[new create destroy]

  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'rooms#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message
  include ActiveModel::Serializers::JSON

  attr_accessor :action,
                :from_class,
                :from_id,
                :to_class,
                :to_id,
                :data

  def initialize(attributes = {})
    @action = attributes[:action]
    @from_class = attributes[:from_class]
    @from_id = attributes[:from_id]
    @to_class = attributes[:to_class]
    @to_id = attributes[:to_id]
    @data = attributes[:data]
  end

  def attributes=(hash)
    hash.each do |key, value|
      send("#{key}=", value)
    end
  end

  def attributes
    instance_values
  end

  class << self
    def build(attributes = nil)
      attributes &&= format(attributes)
      new(attributes)
    end

    private

    def format(attributes)
      {
        action: attributes[:action],
        from_class: attributes[:from]&.class&.name,
        from_id: attributes[:from]&.id,
        to_class: attributes[:to]&.class&.name,
        to_id: attributes[:to]&.id,
        data: attributes[:data].to_json
      }
    end
  end

  # def from
  #   klass = from_class
  #   klass.find_by(id: from_id)
  # end
  # Same as #to method
  %i[from to].each do |name|
    define_method(name) do
      klass = instance_variable_get("@#{name}_class")&.constantize

      return nil unless klass

      klass.find_by(id: public_send("#{name}_id"))
    end
  end

  def broadcast
    channel.broadcast_to(to, self)
  end

  def channel
    return nil unless @to_class

    "#{@to_class}sChannel".constantize
  end

  def deliver
    MessageJob.perform_later(to_json)
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :user

  has_secure_token
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :rooms, dependent: :destroy

  validates :name, allow_blank: false, uniqueness: true

  has_secure_password
  has_secure_password :remember, validations: false

  def self.new_token
    SecureRandom.base58(24)
  end

  def remember
    token = User.new_token
    update(remember: token) && token
  end

  def forget
    update(remember: nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    return if login?

    store_location
    flash[:error] = '请登录'
    redirect_to new_sessions_url
  end
end

app/controllers/concerns/room_message_utils.rb
# frozen_string_literal: true

module RoomMessageUtils
  def create_rooms_message(action, data)
    Message.build(
      action: action,
      data: data,
      from: current_user,
      to: @room
    ).deliver
  end

  def notice(content)
    data = {
      type: 'notice',
      data: "#{current_user.name} #{content}"
    }
    create_rooms_message('broadcast', data)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include RoomMessageUtils

  def create
    content = params[:content]
    notice(content)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :logged_in_user

  def show
    @room = current_user.rooms.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    room = current_user.rooms.find_or_initialize_by(room_params)

    if room.save
      flash[:success] = '房间已创建！'
      redirect_to room
    else
      render 'new'
    end
  end

  def index; end

  def join
    @room = Room.find_by(token: params[:token])

    render 'show' if @room
  end

  private

  def room_params
    params.require(:room).permit(:playlist_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_user, only: %i[destroy]

  def new; end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user&.authenticate(params[:session][:password])
      login @user
      params[:session][:remember_me] ? remember(@user) : forget(@user)
      flash[:success] = '登陆成功'
      redirect_back_or @user
    else
      flash.now[:error] = '用户名或密码错误'
      render 'new'
    end
  end

  def destroy
    logout if login?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, except: %i[new create]

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = '注册成功'
      redirect_to new_sessions_url
    else
      flash[:error] = '注册失败'
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = '更新成功'
      redirect_to rooms_path
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy
    flash[:success] = '删除成功'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    token = user.remember
    return unless token

    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember] = token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember)
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticate_remember(cookies[:remember])
        login(user)
        @current_user = user
      end
    end
  end

  def login?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_console.html.erb
<% if Rails.env.development? %>
  <%= console %>
<% end %>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
      <%= msg %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-column flex-md-row fixed-bottom align-items-center p-2 px-md-4 bg-white border-bottom shadow-sm justify-content-center">
  <small>
      Designed by Dounx
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <a class="navbar-brand my-0 mr-md-auto font-weight-normal text-dark" href="/">Live Music</a>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to '新建房间', new_room_path, class: 'p-2 text-dark' %>
    <%= link_to '加入房间', join_rooms_path, class: 'p-2 text-dark' %>
    <a class="p-2 text-dark" href="https://space.bilibili.com/386290533">哔哩哔哩</a>
    <a class="p-2 text-dark" href="https://blog.dounx.me">博客</a>
    <a class="p-2 text-dark" href="https://github.com/dounx/live-music">GitHub</a>
  </nav>
  <ul class="navbar-nav my-2 my-lg-0">
    <% if login? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.name %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to('房间', rooms_path, class: 'dropdown-item') %>
        <%= link_to('设置', edit_user_path(current_user), class: 'dropdown-item') %>
        <div class="dropdown-divider"></div>
        <%= link_to('退出账号', sessions_path, method: :delete, id: 'logout', class: 'dropdown-item') %>
        <div id="netease-logout"></div>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <%=  link_to('登陆', new_sessions_path, class: 'nav-link')  %>
    </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_rails_default.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live Music</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= render partial: 'layouts/flash', flash: flash %>
      <div class="p-3 px-md-4 mb-3">
        <%= yield %>
        <div id="root"></div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/console' %>
  </body>
</html>

app/views/rooms/index.html.erb
<div id="rooms-index"></div>

app/views/rooms/join.html.erb
<div id="rooms-join"></div>
<div class="wrapper fadeInDown">
  <div id="formContent">
    <div>
      <h2>房间</h2>
    </div>
      <%= text_field_tag :token, nil, placeholder: 'Token', class: 'styled-input' %>
      <%= submit_tag '加入', id: 'join_room', class: 'btn btn-primary' %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <div>
      <h2>房间</h2>
    </div>
    <%= form_for(@room) do |form| %>
      <%= render 'shared/error_messages', object: form.object %>
      <% if @room.errors.any? %>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>

      <%= form.text_field :playlist_id, placeholder: '歌单 ID', class: 'styled-input' %>
      <%= form.submit '创建', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= content_tag :div, nil, id: 'playlist-id', value: @room.playlist_id %>
<div id="room-id" value="<%= @room.id %>"></div>
<div id="is-owner" value=<%= @room.user == current_user %>></div>
<div id="room-token" value=<%= @room.token %>></div>

<div id="rooms-show"></div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      表单中有 <%= object.errors.count %> 个错误
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<% register = local_assigns[:register] %>

<div class="wrapper fadeInDown">
  <div id="formContent">
    <div>
      <h2><%= register ? '注册' : '编辑' %></h2>
    </div>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <% if register %>
        <%= f.text_field :name, autofocus: true, autocomplete: 'username', placeholder: '用户名', class: 'styled-input' %>
      <% end %>

      <%= f.password_field :password, autocomplete: 'new-password', placeholder: '密码', class: 'styled-input' %>

      <%= f.password_field :password_confirmation, autocomplete: 'new-password', placeholder: '确认密码', class: 'styled-input' %>

      <div class="actions">
        <%= f.submit register ? '注册' : '更新' %>
      </div>
    <% end %>

    <% if register %>
      <div id="formFooter">
        <p>已有帐号？<%= link_to '现在登陆', new_sessions_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', register: false %>

app/views/users/new.html.erb
<%= render 'form', register: true %>